[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if extra and extra.playing_cards_created then"
position = "before"
payload = " for _, v in ipairs(SMODS.find_card('j_marcpoke_chatot')) do v.config.center:chatter_boost(v) end"
match_indent = true