[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

#Toxtricity effect... for vanilla jokers?
#[[patches]]
#[patches.pattern]
#target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
#pattern = "if increase then"
#position = "after"
#payload = '''
#    print(#SMODS.find_card("j_marcpoke_toxtricity"))
#    print("inc", increase, increase/2)
#    increase = increase + (increase / 2) * (#SMODS.find_card("j_marcpoke_toxtricity"))
#'''
#match_indent = true#

#Toxtricity effect for pokemon
#[[patches]]
#[patches.pattern]
#target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
#
#pattern = "local bonus_amt = math.ceil(card.ability.extra[field]/(increased and 2 or 1))"
#position = "after"
#payload = '''
#    print(#SMODS.find_card("j_marcpoke_toxtricity"))
#    print("inc", increase, increase/2)
#    bonus_amt = bonus_amt + (bonus_amt / 2) * (#SMODS.find_card("j_marcpoke_toxtricity"))
#'''
#match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
pattern = "local addition = energy_values[name]"
position = "after"
payload = 'addition# = addition + (addition / 2) * (#SMODS.find_card("j_marcpoke_toxtricity"))'
match_indent = true

#[[patches]]#
#[patches.pattern]
#target = "engine/sound_manager.lua"
#pattern = "function RESTART_MUSIC(args)"
#position = "after"
#payload = "print (args)"
#match_indent = true